// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'dart:convert';

class EbooksModel {
  EbooksModel({
    required this.id,
    required this.title,
    required this.author,
    required this.cover_url,
    required this.download_url,
  });

  final int id;
  final String title;
  final String author;
  final String cover_url;
  final String download_url;
  

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'title': title,
      'author': author,
      'cover_url': cover_url,
      'download_url': download_url,
    };
  }

  factory EbooksModel.fromMap(Map<String, dynamic> map) {
     T cast<T>(String k) => map[k] is T ? map[k] as T : throw ArgumentError.value(map[k], k, '$T ← ${map[k].runtimeType}');
    return EbooksModel(
      id: cast<num>('id').toInt(),
      title: cast<String>('title'),
      author: cast<String>('author'),
      cover_url: cast<String>('cover_url'),
      download_url: cast<String>('download_url'),
    );
  }

  String toJson() => json.encode(toMap());

  factory EbooksModel.fromJson(String source) => EbooksModel.fromMap(json.decode(source) as Map<String, dynamic>);
}
